theme: jekyll-theme-minimal
title: Robert McIlrath
logo: "/images/pic.png?raw=true"
round-logo: true
description: 
  <br>
  Blah blah blah blah. Description of me goes here. Please hire me :)
  <br><br>
  <a href="mailto:romcilrath@gmail.com">romcilrath@gmail.com</a>
  <br><br>
  <a href="https://www.linkedin.com/in/robert-mcilrath/">View My LinkedIn Profile</a>
