theme: jekyll-theme-minimal
title: Robert McIlrath
favicon: "/images/favicon.png"
logo: "/images/pic.png?raw=true"
round-logo: true
description: 
  <br>
  Hello, my name is Robert and I am a recent SUNY Albany graduate looking to demonstrate what I have learned. My interest is in software development, with a particular interest in machine learning and data science.
  <br><br>
  <a href="mailto:romcilrath@gmail.com">romcilrath@gmail.com</a>
  <br><br>
  <a href="https://www.linkedin.com/in/robert-mcilrath/">View My LinkedIn Profile</a>
