theme: jekyll-theme-minimal
favicon: "/images/favicon.ico"
title: Robert McIlrath
author: Robert McIlrath
logo: "/images/pic.png?raw=true"
description: 
  <br>
  Welcome!
  <br><br>
  My name is Robert and I am a recent compu sci graduate. My interest is in web development, with a particular interest in full stack development. I would also be very interested in data scientist roles or internships. I'm currently looking for work, so please feel free to reach out!
  <br><br>
  <a href="mailto:romcilrath@gmail.com">romcilrath@gmail.com</a>
  <br><br>
  <a href="https://www.linkedin.com/in/robert-mcilrath/">View My LinkedIn Profile</a>
